services:
  jupyterhub:
    build:
      context: ./jupyterhub
      dockerfile: Dockerfile
    image: sbnpsi/jupyterhub:latest
    restart: unless-stopped
    ports:
      - "80:8000"
      - "8081:8081"
    env_file:
      - /srv/jupyterhub/.env
    volumes:
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
      - jupyterhub-data:/srv/jupyterhub
      - /var/run/docker.sock:/var/run/docker.sock
      - ./files:/srv/jupyterhub/files
      - ./access_control:/srv/jupyterhub/access_control
    networks:
      - jupyterhub_network

  user-notebook:
    build:
      context: ./user-notebook
      dockerfile: Dockerfile
    image: sbnpsi/user-notebook:latest
    networks:
      - jupyterhub_network

volumes:
  jupyterhub-data:

networks:
  jupyterhub_network:
    driver: bridge
